// client/src/components/MessageList.vue
<script setup lang="ts">
import useSessionStore from '@/stores/session';
const sessionStore = useSessionStore();
</script>

<template>
    <div>
        <div class="left">
            <button class="button is-primary" @click="sessionStore.api('non-existent-endpoint')">404 Api</button>
            <button class="button is-primary" @click="sessionStore.api('products/7000')">Error Api</button>
        </div>
        <div class="message-list">
            <div v-for="(message, index) in sessionStore.messages" :key="index"
                 :class="`message is-small is-${message.type}`">
                <p class="message-body">
                    <button class="delete" @click="sessionStore.messages.splice(index, 1)"></button>
                    {{ message.text }}
                </p>
            </div>
        </div>
    </div>
</template>

<style scoped>
.delete {
    float: right;
}
</style>

// react_client_opus/src/components/MessageList.tsx
import { useSessionStore } from '@/stores/session'

export default function MessageList() {
  const messages = useSessionStore((s) => s.messages)
  const removeMessage = useSessionStore((s) => s.removeMessage)

  return (
    <div>
      <div className="message-list">
        {messages.map((message, index) => (
          <div key={index} className={`message is-small is-${message.type}`}>
            <p className="message-body">
              <button className="delete" style={{ float: 'right' }} onClick={() => removeMessage(index)}></button>
              {message.text}
            </p>
          </div>
        ))}
      </div>
    </div>
  )
}
