// react_client_opus/src/components/DialogBoxes.tsx
/* eslint-disable @typescript-eslint/no-explicit-any */
import { useRef, useEffect } from 'react'
import { create } from 'zustand'

type ConfirmState = {
  isOpen: boolean
  title: string
  message: string
  shouldFocus?: boolean
  resolve: (value: any) => void
  reject: (reason: any) => void
}

const useConfirmStore = create<ConfirmState>(() => ({
  isOpen: false,
  title: '',
  message: '',
  shouldFocus: undefined,
  resolve: () => null,
  reject: () => null,
}))

export function confirm(title: string, message: string, shouldFocus?: boolean) {
  return new Promise((resolve, reject) => {
    useConfirmStore.setState({
      isOpen: true,
      title,
      message,
      shouldFocus,
      resolve,
      reject,
    })
  })
}

export default function DialogBoxes() {
  const { isOpen, title, message, shouldFocus, resolve } = useConfirmStore()
  const btnYesRef = useRef<HTMLButtonElement>(null)

  useEffect(() => {
    if (isOpen && shouldFocus) {
      btnYesRef.current?.focus()
    }
  }, [isOpen, shouldFocus])

  function yes() {
    resolve(true)
    useConfirmStore.setState({ isOpen: false })
  }

  function no() {
    resolve(false)
    useConfirmStore.setState({ isOpen: false })
  }

  if (!isOpen) return null

  return (
    <div className="modal is-active">
      <div className="modal-background" onClick={() => useConfirmStore.setState({ isOpen: false })}></div>
      <div className="modal-card">
        <header className="modal-card-head">
          <p className="modal-card-title">{title}</p>
          <button className="delete" aria-label="close" onClick={() => useConfirmStore.setState({ isOpen: false })}></button>
        </header>
        <section className="modal-card-body">
          <p>{message}</p>
        </section>
        <footer className="modal-card-foot">
          <div className="buttons">
            <button className="button is-success" onClick={yes} ref={btnYesRef}>Yes</button>
            <button className="button" onClick={no}>No</button>
          </div>
        </footer>
      </div>
    </div>
  )
}

// client/src/components/DialogBoxes.vue
<!-- eslint-disable @typescript-eslint/no-explicit-any -->
<script lang="ts">
let confirmData: any = null;
export function confirm(title: string, message: string, shouldFocus?: boolean) {
    confirmData.isOpen = true;
    confirmData.title = title;
    confirmData.message = message;
    confirmData.shouldFocus = shouldFocus;

    return new Promise((resolve, reject) => {
        confirmData.resolve = resolve;
        confirmData.reject = reject;
    });
}
</script>

<!-- eslint-disable @typescript-eslint/no-explicit-any -->
<script setup lang="ts">

import { reactive, ref, watch } from 'vue';

const btnYes = ref<HTMLFormElement | null>(null);
confirmData = reactive({
    isOpen: false,
    resolve: (x => null) as (value: any) => void,
    reject: (x => null) as (reason: any) => void,
    title: '',
    message: '',
    shouldFocus: undefined as boolean | undefined,
})
function yes() {
    confirmData.resolve(true);
    confirmData.isOpen = false;
}
function no() {
    confirmData.resolve(false);
    confirmData.isOpen = false;
}
watch(confirmData, (val) => {
    if (val.isOpen && val.shouldFocus) {
        btnYes.value?.focus()
    }
})
</script>

<template>

    <div class="modal is-active" v-if="confirmData.isOpen">
        <div class="modal-background" @click="confirmData.isOpen = false"></div>
        <div class="modal-card">
            <header class="modal-card-head">
                <p class="modal-card-title">{{ confirmData.title }}</p>
                <button class="delete" aria-label="close" @click="confirmData.isOpen = false"></button>
            </header>
            <section class="modal-card-body">
                <p>{{ confirmData.message }}</p>
            </section>
            <footer class="modal-card-foot">
                <div class="buttons">
                    <button class="button is-success" @click="yes()">{{ confirmData.confirmText ?? 'Yes' }}</button>
                    <button class="button" @click="no()">{{ confirmData.cancelText ?? 'No' }}</button>
                </div>
            </footer>
        </div>
    </div>
</template>

<style scoped></style>
