// react_client_opus/src/components/PaginationControls.tsx
import { useMemo } from 'react'

type PaginationControlsProps = {
  currentPage?: number
  totalPages: number
  pageSize?: number
  onPageChange?: (page: number) => void
  onPageSizeChange?: (size: number) => void
}

export default function PaginationControls({
  currentPage = 1,
  totalPages,
  pageSize,
  onPageChange,
  onPageSizeChange,
}: PaginationControlsProps) {
  const current = currentPage ?? 1

  function goTo(page: number) {
    if (page < 1 || page > totalPages) return
    onPageChange?.(page)
  }

  // Build the list of page entries: numbers or 'ellipsis'
  const pages = useMemo(() => {
    const total = totalPages
    const result: (number | 'ellipsis')[] = []

    if (total <= 7) {
      for (let i = 1; i <= total; i++) result.push(i)
      return result
    }

    result.push(1)
    if (current > 3) result.push('ellipsis')
    for (let i = Math.max(2, current - 1); i <= Math.min(total - 1, current + 1); i++) {
      result.push(i)
    }
    if (current < total - 2) result.push('ellipsis')
    result.push(total)

    return result
  }, [totalPages, current])

  return (
    <nav className="pagination is-centered" role="navigation" aria-label="pagination">
      <a
        href="#"
        className={`pagination-previous ${current === 1 ? 'is-disabled' : ''}`}
        onClick={(e) => { e.preventDefault(); goTo(current - 1) }}
      >
        Previous
      </a>
      <a
        href="#"
        className={`pagination-next ${current === totalPages ? 'is-disabled' : ''}`}
        onClick={(e) => { e.preventDefault(); goTo(current + 1) }}
      >
        Next page
      </a>
      <ul className="pagination-list">
        {pages.map((page, i) =>
          page === 'ellipsis' ? (
            <li key={`ellipsis-${i}`}>
              <span className="pagination-ellipsis">&hellip;</span>
            </li>
          ) : (
            <li key={page}>
              <a
                href="#"
                className={`pagination-link ${page === current ? 'is-current' : ''}`}
                aria-label={`Goto page ${page}`}
                aria-current={page === current ? 'page' : undefined}
                onClick={(e) => { e.preventDefault(); goTo(page) }}
              >
                {page}
              </a>
            </li>
          ),
        )}
      </ul>
      {pageSize && (
        <div className="select" style={{ order: 2 }}>
          <select
            value={pageSize}
            onChange={(e) => onPageSizeChange?.(Number(e.target.value))}
          >
            <option value={5}>5 per page</option>
            <option value={10}>10 per page</option>
            <option value={20}>20 per page</option>
            <option value={50}>50 per page</option>
          </select>
        </div>
      )}
    </nav>
  )
}

// client/src/components/PaginationControls.vue
<script setup lang="ts">
import { computed } from 'vue';

const props = defineProps<{
    currentPage: number;
    totalPages: number;
    pageSize?: number;
}>();

const emit = defineEmits<{
    (e: 'update:currentPage', page: number): void;
    (e: 'update:pageSize', size: number): void;
}>();

function goTo(page: number) {
    if (page < 1 || page > props.totalPages) return;
    emit('update:currentPage', page);
}

// Build the list of page entries: numbers or 'ellipsis'
const pages = computed(() => {
    const total = props.totalPages;
    const current = props.currentPage;
    const result: (number | 'ellipsis')[] = [];

    if (total <= 7) {
        for (let i = 1; i <= total; i++) result.push(i);
        return result;
    }

    result.push(1);
    if (current > 3) result.push('ellipsis');
    for (let i = Math.max(2, current - 1); i <= Math.min(total - 1, current + 1); i++) {
        result.push(i);
    }
    if (current < total - 2) result.push('ellipsis');
    result.push(total);

    return result;
});
</script>

<template>
    <nav class="pagination is-centered" role="navigation" aria-label="pagination">
        <a href="#" class="pagination-previous" :class="{ 'is-disabled': currentPage === 1 }"
           @click.prevent="goTo(currentPage - 1)">Previous</a>
        <a href="#" class="pagination-next" :class="{ 'is-disabled': currentPage === totalPages }"
           @click.prevent="goTo(currentPage + 1)">Next page</a>
        <ul class="pagination-list">
            <template v-for="(page, i) in pages" :key="i">
                <li v-if="page === 'ellipsis'">
                    <span class="pagination-ellipsis">&hellip;</span>
                </li>
                <li v-else>
                    <a href="#" class="pagination-link"
                       :class="{ 'is-current': page === currentPage }"
                       :aria-label="`Goto page ${page}`"
                       :aria-current="page === currentPage ? 'page' : undefined"
                       @click.prevent="goTo(page)">{{ page }}</a>
                </li>
            </template>
        </ul>
        <div class="select" v-if="props.pageSize" style="order: 2;">
            <select :value="props.pageSize"
                    @change="emit('update:pageSize', Number(($event.target as HTMLSelectElement)?.value))">
                <option :value="5">5 per page</option>
                <option :value="10">10 per page</option>
                <option :value="20">20 per page</option>
                <option :value="50">50 per page</option>
            </select>
        </div>

    </nav>

</template>

<style scoped></style>
