// react_client_opus/src/views/Admin/UserEdit.tsx
import { useState, useEffect } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { useUsersStore } from '@/stores/users'
import type { User } from '../../../../server/types'

const genders = ['Male', 'Female', 'Other']
const roles = ['Admin', 'User', 'Vendor']

export default function UserEdit() {
  const navigate = useNavigate()
  const { id } = useParams()
  const getUser = useUsersStore((s) => s.getUser)
  const createUser = useUsersStore((s) => s.createUser)
  const updateUser = useUsersStore((s) => s.updateUser)

  const [user, setUser] = useState<User>({} as User)

  useEffect(() => {
    if (id) {
      getUser(Number(id)).then((data) => {
        setUser(data.data)
      })
    }
  }, [id])

  async function saveUser(e: React.FormEvent) {
    e.preventDefault()
    if (user.id) {
      await updateUser(user.id, user)
    } else {
      await createUser(user)
    }
    navigate('/admin/users')
  }

  return (
    <form id="admin-user-edit" className="box" onSubmit={saveUser}>
      <h1 className="title">{user.id ? 'Edit' : 'New'} User</h1>
      <div className="columns">
        <div className="column">
          <div className="field">
            <label className="label">First Name</label>
            <div className="control">
              <input
                className="input"
                type="text"
                value={user.firstName || ''}
                onChange={(e) => setUser({ ...user, firstName: e.target.value })}
              />
            </div>
          </div>
        </div>
        <div className="column">
          <div className="field">
            <label className="label">Last Name</label>
            <div className="control">
              <input
                className="input"
                type="text"
                value={user.lastName || ''}
                onChange={(e) => setUser({ ...user, lastName: e.target.value })}
              />
            </div>
          </div>
        </div>
      </div>
      <div className="field">
        <label className="label">Email</label>
        <div className="control">
          <input
            className="input"
            type="email"
            value={user.email || ''}
            onChange={(e) => setUser({ ...user, email: e.target.value })}
          />
        </div>
      </div>

      <div className="columns">
        <div className="column">
          <div className="field">
            <label className="label">Role</label>
            <div className="control">
              <select
                className="input"
                value={user.role || ''}
                onChange={(e) => setUser({ ...user, role: e.target.value as User['role'] })}
              >
                <option value="">Select role</option>
                {roles.map((role) => (
                  <option key={role} value={role.toLowerCase()}>{role}</option>
                ))}
              </select>
            </div>
          </div>
        </div>
        <div className="column">
          <div className="field">
            <label className="label">Gender</label>
            <div className="control">
              <select
                className="input"
                value={user.gender || ''}
                onChange={(e) => setUser({ ...user, gender: e.target.value })}
              >
                <option value="">Select gender</option>
                {genders.map((gender) => (
                  <option key={gender} value={gender.toLowerCase()}>{gender}</option>
                ))}
              </select>
            </div>
          </div>
        </div>
        <div className="column">
          <div className="field">
            <label className="label">Birth Date</label>
            <div className="control has-icons-left">
              <span className="icon is-small is-left">📅</span>
              <input
                className="input"
                type="date"
                value={user.birthDate || ''}
                onChange={(e) => setUser({ ...user, birthDate: e.target.value })}
              />
            </div>
          </div>
        </div>
      </div>

      <div className="field">
        <label className="label">Avatar URL</label>
        <div className="control">
          <input
            className="input"
            type="text"
            value={user.image || ''}
            onChange={(e) => setUser({ ...user, image: e.target.value })}
          />
        </div>
      </div>
      <div className="field">
        <label className="label">Phone Number</label>
        <div className="control has-icons-left">
          <span className="icon is-small is-left">📞</span>
          <input
            className="input"
            type="tel"
            value={user.phone || ''}
            onChange={(e) => setUser({ ...user, phone: e.target.value })}
          />
        </div>
      </div>

      <div className="columns">
        <div className="column is-three-quarters">
          <div className="field">
            <label className="label">Address</label>
            <div className="control">
              <input
                className="input"
                type="text"
                value={user.address || ''}
                onChange={(e) => setUser({ ...user, address: e.target.value })}
              />
            </div>
          </div>
        </div>
        <div className="column">
          <div className="field">
            <label className="label">Country</label>
            <div className="control">
              <input
                className="input"
                type="text"
                value={user.country || ''}
                onChange={(e) => setUser({ ...user, country: e.target.value })}
              />
            </div>
          </div>
        </div>
      </div>
      <div className="columns">
        <div className="column">
          <div className="field">
            <label className="label">City</label>
            <div className="control">
              <input
                className="input"
                type="text"
                value={user.city || ''}
                onChange={(e) => setUser({ ...user, city: e.target.value })}
              />
            </div>
          </div>
        </div>
        <div className="column">
          <div className="field">
            <label className="label">State</label>
            <div className="control">
              <input
                className="input"
                type="text"
                value={user.state || ''}
                onChange={(e) => setUser({ ...user, state: e.target.value })}
              />
            </div>
          </div>
        </div>
        <div className="column">
          <div className="field">
            <label className="label">ZIP Code</label>
            <div className="control">
              <input
                className="input"
                type="text"
                value={user.postalCode || ''}
                onChange={(e) => setUser({ ...user, postalCode: e.target.value })}
              />
            </div>
          </div>
        </div>
      </div>

      <div className="field is-grouped">
        <div className="control">
          <button className="button is-link" type="submit">Save</button>
        </div>
        <div className="control">
          <button className="button is-light" type="button" onClick={() => navigate('/admin/users')}>Cancel</button>
        </div>
      </div>
    </form>
  )
}

// client/src/views/Admin/UserEdit.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { useUsersStore } from '@/stores/users';

import type { User } from '../../../../server/types';

const router = useRouter();
const route = useRoute();
const users = useUsersStore();
const userId = route.params.id as string;
const user = ref({} as User);

const genders = ['Male', 'Female', 'Other'];
const roles = ['Admin', 'User', 'Vendor'];

if (userId) {
    users.getUser(Number(userId)).then((data) => {
        user.value = data.data
    });
}

async function saveUser() {
    if (user.value.id) {
        await users.updateUser(user.value.id, user.value);
    } else {
        await users.createUser(user.value);
    }

    router.push('/admin/users');
}

</script>

<template>
    <form id="admin-user-edit" class="box" v-if="user" @submit.prevent="saveUser">
        <h1 class="title">{{ user.id ? 'Edit' : 'New' }} User</h1>
        <div class="columns">
            <div class="column">
                <div class="field">
                    <label class="label">First Name</label>
                    <div class="control">
                        <input class="input" type="text" v-model="user.firstName">
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="field">
                    <label class="label">Last Name</label>
                    <div class="control">
                        <input class="input" type="text" v-model="user.lastName">
                    </div>
                </div>
            </div>
        </div>
        <div class="field">
            <label class="label">Email</label>
            <div class="control">
                <input class="input" type="email" v-model="user.email">
            </div>
        </div>

        <div class="columns">
            <div class="column">
                <div class="field">
                    <label class="label">Role</label>
                    <div class="control">
                        <select class="input" v-model="user.role">
                            <option v-for="role in roles" :key="role" :value="role.toLowerCase()">{{ role }}</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="field">
                    <label class="label">Gender</label>
                    <div class="control">
                        <select class="input" v-model="user.gender">
                            <option v-for="gender in genders" :key="gender" :value="gender.toLowerCase()">{{ gender }}
                            </option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="field">
                    <label class="label">Birth Date</label>
                    <div class="control has-icons-left">
                        <span class="icon is-small is-left">📅</span>
                        <input class="input" type="date" v-model="user.birthDate">
                    </div>
                </div>
            </div>
        </div>

        <div class="field">
            <label class="label">Avatar URL</label>
            <div class="control">
                <input class="input" type="text" v-model="user.image">
            </div>
        </div>
        <div class="field">
            <label class="label">Phone Number</label>
            <div class="control has-icons-left">
                <span class="icon is-small is-left">📞</span>
                <input class="input" type="tel" v-model="user.phone">
            </div>
        </div>


        <div class="columns">
            <div class="column is-three-quarters">
                <div class="field">
                    <label class="label">Address</label>
                    <div class="control">
                        <input class="input" type="text" v-model="user.address">
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="field">
                    <label class="label">Country</label>
                    <div class="control">
                        <input class="input" type="text" v-model="user.country">
                    </div>
                </div>
            </div>
        </div>
        <div class="columns">
            <div class="column">
                <div class="field">
                    <label class="label">City</label>
                    <div class="control">
                        <input class="input" type="text" v-model="user.city">
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="field">
                    <label class="label">State</label>
                    <div class="control">
                        <input class="input" type="text" v-model="user.state">
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="field">
                    <label class="label">ZIP Code</label>
                    <div class="control">
                        <input class="input" type="text" v-model="user.postalCode">
                    </div>
                </div>
            </div>
        </div>

        <div class="field is-grouped">
            <div class="control">
                <button class="button is-link">Save</button>
            </div>
            <div class="control">
                <button class="button is-light">Cancel</button>
            </div>
        </div>

    </form>
</template>

<style scoped></style>
